name: ambisis_dashboard_challenge
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_riverpod: ^2.3.4
  intl: ^0.17.0
  random_x: ^0.3.1
  sqflite: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
